In [77]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [78]:
df=pd.read_csv("Real estate.csv")
df.columns

Index(['No', 'X1 transaction date', 'X2 house age',
       'X3 distance to the nearest MRT station',
       'X4 number of convenience stores', 'X5 latitude', 'X6 longitude',
       'Y house price of unit area'],
      dtype='object')

In [79]:
x = df[['X2 house age','X3 distance to the nearest MRT station','X4 number of convenience stores', 'X5 latitude', 'X6 longitude']]
y = df['Y house price of unit area']

In [80]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,train_size=0.8, random_state=42)

In [68]:
train_test_split(x,y,test_size=0.2,random_state=42)

[     X2 house age  X3 distance to the nearest MRT station  \
 192          43.8                                57.58945   
 234           8.0                              2216.61200   
 5             7.1                              2175.03000   
 45           36.6                               488.81930   
 245           7.5                               639.61980   
 ..            ...                                     ...   
 71           35.5                               640.73910   
 106          17.2                               189.51810   
 270          10.8                               252.58220   
 348           4.6                               259.66070   
 102           1.1                               193.58450   
 
      X4 number of convenience stores  X5 latitude  X6 longitude  
 192                                7     24.96750     121.54069  
 234                                4     24.96007     121.51361  
 5                                  3     24.96305   

In [69]:
poly = PolynomialFeatures(degree=2)
xpoly = poly.fit_transform(xtrain)
xpoly

array([[1.00000000e+00, 4.38000000e+01, 5.75894500e+01, ...,
        6.23376056e+02, 3.03456718e+03, 1.47721393e+04],
       [1.00000000e+00, 8.00000000e+00, 2.21661200e+03, ...,
        6.23005094e+02, 3.03298821e+03, 1.47655574e+04],
       [1.00000000e+00, 7.10000000e+00, 2.17503000e+03, ...,
        6.23153865e+02, 3.03332361e+03, 1.47652974e+04],
       ...,
       [1.00000000e+00, 1.08000000e+01, 2.52582200e+02, ...,
        6.23730645e+02, 3.03517463e+03, 1.47696527e+04],
       [1.00000000e+00, 4.60000000e+00, 2.59660700e+02, ...,
        6.23793083e+02, 3.03569368e+03, 1.47732259e+04],
       [1.00000000e+00, 1.10000000e+00, 1.93584500e+02, ...,
        6.23286676e+02, 3.03435461e+03, 1.47721879e+04]], shape=(331, 21))

In [70]:
model = LinearRegression()
model.fit(xpoly,ytrain)    
# model.score(xtest,ytest)
xtestpoly = poly.transform(xtest)
# model.predict(xtest)
xtestpoly

array([[1.00000000e+00, 1.10000000e+00, 1.93584500e+02, ...,
        6.23286676e+02, 3.03435461e+03, 1.47721879e+04],
       [1.00000000e+00, 1.32000000e+01, 4.92231300e+02, ...,
        6.23258715e+02, 3.03419867e+03, 1.47713323e+04],
       [1.00000000e+00, 0.00000000e+00, 2.74014400e+02, ...,
        6.23740635e+02, 3.03520218e+03, 1.47696843e+04],
       ...,
       [1.00000000e+00, 1.61000000e+01, 8.15931400e+02, ...,
        6.23943447e+02, 3.03579676e+03, 1.47706687e+04],
       [1.00000000e+00, 1.56000000e+01, 2.89324800e+02, ...,
        6.24101823e+02, 3.03640286e+03, 1.47728175e+04],
       [1.00000000e+00, 1.15000000e+01, 1.36013900e+03, ...,
        6.22604300e+02, 3.03288104e+03, 1.47740184e+04]], shape=(83, 21))

In [71]:
xpoly

array([[1.00000000e+00, 4.38000000e+01, 5.75894500e+01, ...,
        6.23376056e+02, 3.03456718e+03, 1.47721393e+04],
       [1.00000000e+00, 8.00000000e+00, 2.21661200e+03, ...,
        6.23005094e+02, 3.03298821e+03, 1.47655574e+04],
       [1.00000000e+00, 7.10000000e+00, 2.17503000e+03, ...,
        6.23153865e+02, 3.03332361e+03, 1.47652974e+04],
       ...,
       [1.00000000e+00, 1.08000000e+01, 2.52582200e+02, ...,
        6.23730645e+02, 3.03517463e+03, 1.47696527e+04],
       [1.00000000e+00, 4.60000000e+00, 2.59660700e+02, ...,
        6.23793083e+02, 3.03569368e+03, 1.47732259e+04],
       [1.00000000e+00, 1.10000000e+00, 1.93584500e+02, ...,
        6.23286676e+02, 3.03435461e+03, 1.47721879e+04]], shape=(331, 21))

In [72]:
xpoly.shape[0]

331

In [73]:
model.score(xtestpoly,ytest)

0.7510041114955954

In [74]:
d=pd.DataFrame({'X2 house age':[12],'X3 distance to the nearest MRT station':[20],'X4 number of convenience stores':[5],'X5 latitude':[30], 'X6 longitude':[40]})

In [75]:
dtest = poly.transform(d)

In [76]:
model.predict(dtest)

array([6555785.27063003])